
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.Collections;
import static javafx.scene.text.Font.font;

public class Frame extends javax.swing.JFrame {

//    ArrayList<Process> al;
    ReadyQue al;
    int processCount=6;
    int max_time=800;
    private int xaxis=100,yaxis=600;
    // one time unit is equal to 40pts on x_axis
    // one process unit is 50pts on y_axis
    private int xscale=40,yscale=50;
    
    
    public Frame(ReadyQue rq) {
        initComponents();
        al=rq;
        Collections.sort(al,new SortById());
        setTitle("Gantt Chart");
//        al= new ArrayList<Process>(); 
//      	Process p1=new Process();
//       p1.start.add(0);
//       p1.end.add(1);
//       p1.start.add(5);
//       p1.end.add(20);
//        al.add(p1);
//      
//      Process p2=new Process();
//       p2.start.add(2);
//       p2.end.add(5);
//       p2.start.add(10);
//       p2.end.add(11);
//        al.add(p2);
//      
//      Process p3=new Process();
//       p3.start.add(0);
//       p3.end.add(5);
//       p3.start.add(8);
//       p3.end.add(10);
//       al.add(p3);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("                time");

        jLabel2.setFont(new java.awt.Font("Adobe Caslon Pro", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 255));
        jLabel2.setText("Visual Timeline Representation");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(373, 373, 373)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(352, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 532, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    Color array[]= {Color.MAGENTA,Color.blue,Color.YELLOW,Color.DARK_GRAY,Color.cyan};
    @Override
    public void paint(Graphics g)
    {
        super.paint(g);
        g.drawLine(xaxis, 100, xaxis, yaxis);
        g.drawLine(xaxis, yaxis,1000,yaxis);
        
        for(int i =0;i<al.size();i++)
        {
          Process p = al.get(i);
          g.setColor(Color.BLACK);
          g.drawString("process"+(i+1), 20, (yaxis+10-(yscale*(i+1))));
          for(int j=0;j<p.start.size();j++)
          {
              
            g.setColor(array[i%array.length]);
            g.fillRect((xaxis+(p.start.get(j)*xscale)), (yaxis-(yscale*(i+1))), (p.end.get(j)-p.start.get(j))*xscale, 20);
          }
            
        }
        int pixel=100;
        g.setColor(Color.BLACK);
        for(int i=0;i<23;i++)
        {
            g.drawString(""+i, pixel+(i*xscale), yaxis+15);
        }
//        g.setColor(Color.decode(""));
//        g.setFont(new Font("Arial", 0, 24));
//        g.drawString("Visual Timeline Representation ", 200, 70);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Frame().setVisible(true);
//            }
//        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
